### PR TITLE
fix: auto-close debug terminal after finished or closed

### LINKED ISSUE #1423: [BUG] 不兼容 JavaScript Debugger 1.68.0
在 OpenSumi 2.18.15 上，无法启动 JavaScript Debugger Terminal

### LINKED ISSUE #1637: [BUG] 进程退出后终端类型调试不会自动终止
**描述你的问题（Describe the bug）**

运行框架内调试测试的调试功能，进程退出后调试进程无法自动关闭

**复现路径（To Reproduce）**

Jest Current Test

**预期表现（Expected behavior）**

正常响应进程退出状态

**问题截图（Screenshots）**

image

### PR DESCRIPTION
**Pull request by erha19**
### Types

- [x] 🐛 Bug Fixes
- [x] 💄 Style Changes

### Background or solution

兼容 JavaScript Debugger 插件至最新 1.71.0 版本，解决调试终端不退出问题

close #1637.
close #1423.

### Changelog

auto-close debug terminal after finished or closed

### CODE REVIEW

File: packages/debug/src/browser/debug-session.ts [hunk 1]
```diff
@@ -315,17 +316,16 @@ export class DebugSession implements IDebugSession {
   protected async runInTerminal({
     arguments: { title, cwd, args, env },
   }: DebugProtocol.RunInTerminalRequest): Promise<DebugProtocol.RunInTerminalResponse['body']> {
-    return this.doRunInTerminal({ name: title, cwd, env }, args.join(' '));
+    return this.doRunInTerminal({ name: title, cwd, env, args });
```
Comment (erha19) [inline packages/debug/src/browser/debug-session.ts:319]: 核心原因是这里不能简单把 args 进行字符串拼接，而是需要组合成 `cd {cwd};  /usr/bin/env {env}; ....{args}` 这种方式来让调试进程能通过参数稳定渠道调试通信路径及环境变量
